#version: '3.8'
#services:
#  mysql-springbootsaleapp-container:
#    image: mysql:8.0.18
#    container_name: mysql-springbootsaleapp-container
#    ports:
#      - 3308:3306    
#    volumes:
#      - mysql-springbootsaleapp-data:/var/lib/mysql
#      - mysql-springbootsaleapp-config-deamond:/etc/mysql/conf.d
#    networks:
#      - backend
#    environment:
#      driverClassName: com.mysql.cj.jdbc.Driver
#      MYSQL_USER: hiep
#      MYSQL_PASSWORD: Admin@123
#      MYSQL_ROOT_PASSWORD: Admin@123
#      MYSQL_DATABASE: saleappdb
#      SPRING_PROFILES_ACTIVE: prod
#  springboot-docker-container:
#    image: newbie2106/springbootsaleapp-docker-container:1.0.0
#    container_name: springbootsaleapp-docker-container
#    ports:
#      - 8083:8080
#    depends_on:
#      - mysql-springbootsaleapp-container
#    volumes:
#      - ./:/app
#    networks:
#      - backend
##create network     
#networks:
#  backend:
#    name: springbootsaleapp-app-network
#volumes:
#  mysql-springbootsaleapp-data:
#  mysql-springbootsaleapp-config-deamond:
    
    
version: '3.8'
services:
  tomcat:
    image: newbie2106/springbootsaleapp-docker-container:1.0.0
    container_name: springbootsaleapp-docker-container
    ports:
      - "8083:8080"
    volumes:
      - ./target/SaleWebsiteQLDA-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0.18
    container_name: mysql-springbootsaleapp-container
    environment:
      MYSQL_USER: hiep
      MYSQL_PASSWORD: Admin@123
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: saleappdb
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql/conf.d
    networks:
      - backend

networks:
  backend:
    name: springbootsaleapp-app-network

volumes:
  mysql-data:
  mysql-config:
